micronaut:
  application:
    name: demo
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    authentication: cookie
    redirect:
        login-failure: /authFailed
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        cookie:
          enabled: true
  io:
    watch:
      paths: src/main
      restart: true
datasources:
  default:
    url: jdbc:mysql://localhost:33306/g_exam_gateway
    username: test
    password: test
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    schema-generate: CREATE_DROP
#    dialect: H2
grpc:
  server:
    port: 18080
  channels:
    question:
      address: 'localhost:55550'
      plaintext: true
      max-retry-attempts: 10
    score:
      address: 'localhost:58000'
      plaintext: true
      max-retry-attempts: 10